version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  users_service:
    build: ./Users
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: pswd
      MYSQL_DATABASE: users
      JWT_SECRET: SECRET_KEY
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      SERVER_PORT_USER: 8080
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: user_events

  products_service:
    build: ./Products
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT_PRODUCT: 8082
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: products
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: product_events

  payment_service:
    build: ./Payment
    ports:
      - "8081:8081"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: payment
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: payment_events

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: users
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: pswd
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: payment
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
