openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: API documentation for the User service.
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /signup:
    post:
      summary: Create a new user
      requestBody:
        description: User data to create a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserReq'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserRes'
        '400':
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict (email already exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /login:
    post:
      summary: Login a user
      requestBody:
        description: User credentials for login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserReq'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUserRes'
        '400':
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized (invalid credentials)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateUserReq:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          example: john_doe
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          format: password
          example: mysecurepassword

    CreateUserRes:
      type: object
      properties:
        id:
          type: string
          example: "1"
        username:
          type: string
          example: john_doe
        email:
          type: string
          example: john@example.com

    LoginUserReq:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          format: password
          example: mysecurepassword

    LoginUserRes:
      type: object
      properties:
        id:
          type: string
          example: "1"
        username:
          type: string
          example: john_doe
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: An error occurred

    ErrorResponseDetail:
      type: object
      properties:
        error:
          type: string
          examples:
            EmptyFields:
              value: "email and username cannot be empty"
            EmailExists:
              value: "email already exists"
            InvalidCredentials:
              value: "invalid credentials"
            TryLoginAgain:
              value: "try to login again"
